-- This file was generated by LetItGo.
local name = "letitgo"
local version = "0.10.0"

food = {
    name = name,
    description = "LetItGo automates releases.",
    homepage = "https://github.com/NoUseFreak/letitgo",
    version = version,
    packages = {
        {
            os = "darwin",
            arch = "amd64",
            url = "https://github.com/NoUseFreak/letitgo/releases/download/0.8.3/darwin_amd64.zip",
            sha256 = "4df069b249a945086028b204b6dad495cf71de54d79f3688f2d8b9b871610dfe",
            resources = {
                {
                    path = name,
                    installpath = "bin/" .. name,
                    executable = true
                }
            }
        },
        {
            os = "linux",
            arch = "amd64",
            url = "https://github.com/NoUseFreak/letitgo/releases/download/0.8.3/linux_amd64.zip",
            sha256 = "b72c680f1e278bb1b581cbf884ed1ebe78ea8b6a14d528feeeb7cc79af3927b7",
            resources = {
                {
                    path = name,
                    installpath = "bin/" .. name,
                    executable = true
                }
            }
        },
        {
            os = "linux",
            arch = "i386",
            url = "https://github.com/NoUseFreak/letitgo/releases/download/0.8.3/linux_386.zip",
            sha256 = "7199fb7ce8ed5e3239b488f0bf79f7be855921b01eea8f0b8fbaf0f0480c911a",
            resources = {
                {
                    path = name,
                    installpath = "bin/" .. name,
                    executable = true
                }
            }
        },
        {
            os = "linux",
            arch = "arm64",
            url = "https://github.com/NoUseFreak/letitgo/releases/download/0.8.3/linux_arm.zip",
            sha256 = "65bfc8f3fedae7373fe59e24e1e24e5aa6c722b5544d67e8dd06b768824b8b08",
            resources = {
                {
                    path = name,
                    installpath = "bin/" .. name,
                    executable = true
                }
            }
        }
    }
}

