-- This file was generated by LetItGo.
local name = "sdf"
local version = "0.2.1"

food = {
    name = name,
    description = "sdf for the lazy developer",
    homepage = "https://github.com/NoUseFreak/sdf",
    version = version,
    packages = {
        {
            os = "darwin",
            arch = "amd64",
            url = "https://github.com/NoUseFreak/sdf/releases/download/0.2.1/darwin_amd64.zip",
            sha256 = "11e67442c726217d78bf0d3d070a1b3452e85ff334433d68fcd3612a5da763bb",
            resources = {
                {
                    path = name,
                    installpath = "bin/" .. name,
                    executable = true
                }
            }
        },
        {
            os = "linux",
            arch = "amd64",
            url = "https://github.com/NoUseFreak/sdf/releases/download/0.2.1/linux_amd64.zip",
            sha256 = "957f87ab65c8b67315cd6fd3d4157189cd2e687e3318d171ade230dd6698af64",
            resources = {
                {
                    path = name,
                    installpath = "bin/" .. name,
                    executable = true
                }
            }
        },
        {
            os = "windows",
            arch = "amd64",
            url = "https://github.com/NoUseFreak/sdf/releases/download/0.2.1/windows_amd64.zip",
            sha256 = "d74cb7cc66e3aa929bc0b10d5fa16d9616816c188d987a36b76492da770dca15",
            resources = {
                {
                    path = name,
                    installpath = "bin/" .. name,
                    executable = true
                }
            }
        }
    }
}

