-- This file was generated by LetItGo.
local name = "sdf"
local version = "0.3.0"

food = {
    name = name,
    description = "sdf for the lazy developer",
    homepage = "https://github.com/NoUseFreak/sdf",
    version = version,
    packages = {
        {
            os = "darwin",
            arch = "amd64",
            url = "https://github.com/NoUseFreak/sdf/releases/download/0.3.0/darwin_amd64.zip",
            sha256 = "f1ee6d6e2b11887e8c3ddcc6e29a6a05ba1b93ad863a5aef005962e2978f63f6",
            resources = {
                {
                    path = name,
                    installpath = "bin/" .. name,
                    executable = true
                }
            }
        },
        {
            os = "linux",
            arch = "amd64",
            url = "https://github.com/NoUseFreak/sdf/releases/download/0.3.0/linux_amd64.zip",
            sha256 = "04ff6430d65f847e2cb3a5a15e234772a31a52c3cd45e2bf39736a752c2a2f4a",
            resources = {
                {
                    path = name,
                    installpath = "bin/" .. name,
                    executable = true
                }
            }
        },
        {
            os = "windows",
            arch = "amd64",
            url = "https://github.com/NoUseFreak/sdf/releases/download/0.3.0/windows_amd64.zip",
            sha256 = "1d2dc2e11a3a992b08a83115a3aa79c2797d79a8d9f2ed987e7808bdc217755a",
            resources = {
                {
                    path = name,
                    installpath = "bin/" .. name,
                    executable = true
                }
            }
        }
    }
}

